# Generated by Django 5.0.3 on 2024-03-09 12:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='a.png', upload_to=api.models.upload_games, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
